import { Lesson, Mentee, Buddy, User } from './types';

export const MOCK_LESSONS: Lesson[] = [
  {
    id: '1',
    title: 'Git Workflow Essentials',
    description: 'Basic branching and PR rules',
    department: 'Engineering',
    modules: 8,
    status: 'Published',
    lastModified: 'Oct 24, 2023',
    icon: 'terminal',
  },
  {
    id: '2',
    title: 'Brand Voice Guide',
    description: 'Maintaining consistency in copy',
    department: 'Marketing',
    modules: 5,
    status: 'Published',
    lastModified: 'Oct 20, 2023',
    icon: 'campaign',
  },
  {
    id: '3',
    title: 'CRM Basics',
    description: 'Introduction to lead tracking',
    department: 'Sales',
    modules: 12,
    status: 'Draft',
    lastModified: 'Oct 22, 2023',
    icon: 'hub',
  },
  {
    id: '4',
    title: 'Figma Components',
    description: 'Design system library usage',
    department: 'Design',
    modules: 6,
    status: 'Published',
    lastModified: 'Oct 15, 2023',
    icon: 'pentagon',
  },
];

export const MOCK_MENTEES: Mentee[] = [
  {
    id: '1',
    name: 'Sarah Kim',
    role: 'Junior Frontend Developer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    progress: 35,
    lastActive: '14 mins ago',
    status: 'Blocked',
    blockedReason: 'Sarah is missing access to the staging environment credentials. Intervention required from DevOps.',
  },
  {
    id: '2',
    name: 'Alex Rivera',
    role: 'Growth Marketer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    progress: 82,
    lastActive: '2 hours ago',
    status: 'On Track',
  },
  {
    id: '3',
    name: 'David Chen',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    progress: 60,
    lastActive: 'Yesterday',
    status: 'On Track',
  },
  {
    id: '4',
    name: 'Emma Watson',
    role: 'Systems Engineer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    progress: 12,
    lastActive: '3 days ago',
    status: 'Needs Attention',
  },
];

export const MOCK_BUDDIES: Buddy[] = [
  {
    id: '1',
    name: 'Alex Rivers',
    role: 'Senior Developer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    rating: 4.9,
    activeMentees: 1,
    maxMentees: 3,
    isOnline: true,
    tags: ['React Expert', 'Architecture'],
  },
  {
    id: '2',
    name: 'Maya Isabella',
    role: 'Lead Designer',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    rating: 5.0,
    activeMentees: 2,
    maxMentees: 3,
    isOnline: false,
    tags: ['UI/UX', 'Design Systems'],
  },
  {
    id: '3',
    name: 'Jordan Smith',
    role: 'Project Manager',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    rating: 4.7,
    activeMentees: 0,
    maxMentees: 3,
    isOnline: true,
    tags: ['Agile', 'Scrum'],
  },
];

export const RECENT_REGISTRATIONS: User[] = [
  {
    id: '1',
    name: 'Sarah Jenkins',
    role: 'Product Designer',
    email: 'sarah.j@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    registrationDate: 'Oct 24, 2023',
    verificationStatus: 'Verified',
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'Backend Engineer',
    email: 'm.chen@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    registrationDate: 'Oct 23, 2023',
    verificationStatus: 'Pending',
  },
  {
    id: '3',
    name: 'Emma Watson',
    role: 'Marketing Lead',
    email: 'e.watson@example.com',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    registrationDate: 'Oct 22, 2023',
    verificationStatus: 'Verified',
  },
  {
    id: '4',
    name: 'David Miller',
    role: 'QA Specialist',
    email: 'd.miller@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    registrationDate: 'Oct 21, 2023',
    verificationStatus: 'Verified',
  },
];
